//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minesweeper.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Minesweeper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Клетка.
        /// </summary>
        internal static string Cell {
            get {
                return ResourceManager.GetString("Cell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сапёр.
        /// </summary>
        internal static string DefaultGameFormName {
            get {
                return ResourceManager.GetString("DefaultGameFormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отличный вариант для первого прохождения.
        /// </summary>
        internal static string Difficulty0Description {
            get {
                return ResourceManager.GetString("Difficulty0Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новичок.
        /// </summary>
        internal static string Difficulty0Name {
            get {
                return ResourceManager.GetString("Difficulty0Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уже умеете играть? Тогда эта сложность для вас.
        /// </summary>
        internal static string Difficulty1Description {
            get {
                return ResourceManager.GetString("Difficulty1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Любитель.
        /// </summary>
        internal static string Difficulty1Name {
            get {
                return ResourceManager.GetString("Difficulty1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проверьте свои силы на минном поле реальной сложности.
        /// </summary>
        internal static string Difficulty2Description {
            get {
                return ResourceManager.GetString("Difficulty2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Профи.
        /// </summary>
        internal static string Difficulty2Name {
            get {
                return ResourceManager.GetString("Difficulty2Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 875 клеток, 300 мин. Один шанс. Ты точно этого хочешь?.
        /// </summary>
        internal static string Difficulty3Description {
            get {
                return ResourceManager.GetString("Difficulty3Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на БЕЗУМИЕ.
        /// </summary>
        internal static string Difficulty3Name {
            get {
                return ResourceManager.GetString("Difficulty3Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Лампочка разбилась... 
        ///У Нико не было второго шанса, и этот мир угас навсегда. 
        ///Тебе не удалось его спасти, .
        /// </summary>
        internal static string EndDialogLose1 {
            get {
                return ResourceManager.GetString("EndDialogLose1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хочешь попытаться восстановить мир из пепла?.
        /// </summary>
        internal static string EndDialogLose2 {
            get {
                return ResourceManager.GetString("EndDialogLose2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нико донёс Солнце до самой вершины!
        ///Свет вернулся в этот мир, и теперь все будет хорошо.
        ///Мы справились, .
        /// </summary>
        internal static string EndDialogWin1 {
            get {
                return ResourceManager.GetString("EndDialogWin1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хочешь пережить это приключение снова?.
        /// </summary>
        internal static string EndDialogWin2 {
            get {
                return ResourceManager.GetString("EndDialogWin2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мировая Машина столкнулась с критической ошибкой. Пожалуйста сообщите разработчику. .
        /// </summary>
        internal static string ErrorMsgBox {
            get {
                return ResourceManager.GetString("ErrorMsgBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле.
        /// </summary>
        internal static string Field {
            get {
                return ResourceManager.GetString("Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Флаг.
        /// </summary>
        internal static string Flag {
            get {
                return ResourceManager.GetString("Flag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сапёр — игра несложная.
        ///Она полностью построена на логике и иногда на везении.
        ///
        ///Твоя цель — открыть всё игровое поле,
        ///пометив места с минами флажками 🚩.
        ///
        ///Левой кнопкой мыши открывай клетки.
        ///Правой кнопкой мыши ставь или убирай флаг.
        ///
        ///Если ты открыл клетку с миной — игра окончена.
        ///Цифры в клетках показывают, сколько мин находится рядом с этой клеткой.
        ///Будь внимателен, думай наперёд и постарайся очистить всё поле без ошибок.
        ///
        ///Удачи, .
        /// </summary>
        internal static string HowToPlayText {
            get {
                return ResourceManager.GetString("HowToPlayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мины.
        /// </summary>
        internal static string Mines {
            get {
                return ResourceManager.GetString("Mines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тебе стоит отдохнуть... может взять перерыв и поспать? Уже .
        /// </summary>
        internal static string NightMessage1 {
            get {
                return ResourceManager.GetString("NightMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  ночи. Спокойной ночи. Пойдёшь спать?.
        /// </summary>
        internal static string NightMessage2 {
            get {
                return ResourceManager.GetString("NightMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Иди спать, .
        /// </summary>
        internal static string NightMessageTitle {
            get {
                return ResourceManager.GetString("NightMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap niko_message {
            get {
                object obj = ResourceManager.GetObject("niko_message", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ты еще тут, .
        /// </summary>
        internal static string Scare1 {
            get {
                return ResourceManager.GetString("Scare1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Судьба мира.
        /// </summary>
        internal static string World_sFate {
            get {
                return ResourceManager.GetString("World\'sFate", resourceCulture);
            }
        }
    }
}
